/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Decathlon.gui;

import Decathlon.dto.Cliente;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Datos2 extends javax.swing.JDialog {
    private Datos1 datos1;
    
    private String deportes;
    private String tallaRopa;
    private String tallaPie;
    private boolean condiciones;
    private JCheckBox[] checkBoxes;  // Agregar esta línea

    
    
    /**
     * Creates new form Datos2
     */
    public Datos2(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        datos1 = (Datos1) parent;
        parent.setVisible(false);
        this.setAlwaysOnTop(true);
        initComponents();
        
        // Agregar todos los campos CheckBox a un arreglo
        checkBoxes = new JCheckBox[]{
            cbFitness, cbAcuaticos, cbEquipo, cbRunning, cbRaqueta, cbCiclismo,
            cbOutdoor, cbInvierno, cbPatines, cbPrecision, cbCombate, cbBaile
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo2 = new javax.swing.JLabel();
        lb_Deportes = new javax.swing.JLabel();
        lb_TallaRopa = new javax.swing.JLabel();
        lb_TallaPie = new javax.swing.JLabel();
        bt_Cancelar = new javax.swing.JButton();
        bt_Finalizar = new javax.swing.JButton();
        lb_Pagina = new javax.swing.JLabel();
        cb_TallaPie = new javax.swing.JComboBox<>();
        cb_TallaRopa = new javax.swing.JComboBox<>();
        checkBoxTerminos = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cbFitness = new javax.swing.JCheckBox();
        cbAcuaticos = new javax.swing.JCheckBox();
        cbEquipo = new javax.swing.JCheckBox();
        cbRunning = new javax.swing.JCheckBox();
        cbRaqueta = new javax.swing.JCheckBox();
        cbCiclismo = new javax.swing.JCheckBox();
        cbOutdoor = new javax.swing.JCheckBox();
        cbInvierno = new javax.swing.JCheckBox();
        cbPatines = new javax.swing.JCheckBox();
        cbPrecision = new javax.swing.JCheckBox();
        cbCombate = new javax.swing.JCheckBox();
        cbBaile = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo2.setBackground(new java.awt.Color(51, 102, 255));
        lbTitulo2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lbTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo2.setText("DATOS EXTRAS");
        lbTitulo2.setOpaque(true);

        lb_Deportes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Deportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Deportes.setText("Deportes");

        lb_TallaRopa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_TallaRopa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TallaRopa.setText("Talla Ropa:");

        lb_TallaPie.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_TallaPie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TallaPie.setText("Talla Pie:");

        bt_Cancelar.setBackground(new java.awt.Color(255, 153, 153));
        bt_Cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bt_Cancelar.setText("Cancelar");
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        bt_Finalizar.setBackground(new java.awt.Color(204, 255, 204));
        bt_Finalizar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bt_Finalizar.setText("Finalizar");
        bt_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FinalizarActionPerformed(evt);
            }
        });

        lb_Pagina.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Pagina.setText("Página 2/2");

        cb_TallaPie.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cb_TallaPie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 35", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "Más de 45" }));

        cb_TallaRopa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cb_TallaRopa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));

        checkBoxTerminos.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        checkBoxTerminos.setText("Acepto los términos y condiciones de Decathlon.");

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        cbFitness.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbFitness.setText("Fitness");

        cbAcuaticos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbAcuaticos.setText("Deportes Acuáticos");

        cbEquipo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbEquipo.setText("Deportes Equipo");

        cbRunning.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbRunning.setText("Running/Caminar");

        cbRaqueta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbRaqueta.setText("Deportes de Raqueta");

        cbCiclismo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbCiclismo.setText("Ciclismo");
        cbCiclismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCiclismoActionPerformed(evt);
            }
        });

        cbOutdoor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbOutdoor.setText("Outdoor");

        cbInvierno.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbInvierno.setText("Deportes Invierno");

        cbPatines.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbPatines.setText("Patines");

        cbPrecision.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbPrecision.setText("Deportes Precisión");

        cbCombate.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbCombate.setText("Deportes de combate");

        cbBaile.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbBaile.setText("Baile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCiclismo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOutdoor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFitness, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPrecision))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAcuaticos)
                    .addComponent(cbRaqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPatines)
                    .addComponent(cbBaile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAcuaticos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiclismo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOutdoor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFitness, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRaqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPatines, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBaile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lb_Pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxTerminos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(bt_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_TallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_TallaPie, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_TallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_TallaPie, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(lb_Deportes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lb_Deportes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_TallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TallaPie, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_TallaPie, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkBoxTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_Pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(685, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbCiclismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCiclismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCiclismoActionPerformed

    private void bt_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FinalizarActionPerformed
        if(checkBoxTerminos.isSelected()){
            //Crear el nuevo cliente, todos los datos han sido validados, llegados a este paso, solo queda almacenarlo
            String nombre = datos1.getNombre();
            String apellidos = datos1.getApellidos();
            Integer edad = datos1.getEdad();
            String genero = datos1.getGenero();
            String dni = datos1.getDni();
            String correo = datos1.getCorreo();

            if(comprobarDeportes()){
                tallaRopa = cb_TallaRopa.getSelectedItem().toString();
                tallaPie = cb_TallaPie.getSelectedItem().toString();
                condiciones = checkBoxTerminos.isSelected();

                Cliente nuevoCliente = new Cliente(nombre, apellidos, genero, dni, correo, deportes, tallaRopa, tallaPie, edad, condiciones);
                PantallaPrincipal pantallaPrincipal = (PantallaPrincipal) datos1.getParent();
                pantallaPrincipal.anadirCliente(nuevoCliente);

                datos1.dispose();
                this.dispose();
            }
            
        } else{
            JOptionPane.showMessageDialog(this, "Debe aceptar los términos y condiciones para poder darse de alta", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_bt_FinalizarActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        datos1.dispose();
        this.dispose();
    }//GEN-LAST:event_bt_CancelarActionPerformed

    private boolean comprobarDeportes(){
        StringBuilder respuesta = new StringBuilder();

        for (JCheckBox checkBox : checkBoxes) {
            if (checkBox.isSelected()) {
                if (respuesta.length() > 0) {
                    respuesta.append(", ");
                }
                respuesta.append(checkBox.getText());
            }
        }
        
        if(respuesta.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe elegir 1 o más categorías de deportes", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        } else{
            this.deportes = respuesta.toString();
            return true;
        }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_Finalizar;
    private javax.swing.JCheckBox cbAcuaticos;
    private javax.swing.JCheckBox cbBaile;
    private javax.swing.JCheckBox cbCiclismo;
    private javax.swing.JCheckBox cbCombate;
    private javax.swing.JCheckBox cbEquipo;
    private javax.swing.JCheckBox cbFitness;
    private javax.swing.JCheckBox cbInvierno;
    private javax.swing.JCheckBox cbOutdoor;
    private javax.swing.JCheckBox cbPatines;
    private javax.swing.JCheckBox cbPrecision;
    private javax.swing.JCheckBox cbRaqueta;
    private javax.swing.JCheckBox cbRunning;
    private javax.swing.JComboBox<String> cb_TallaPie;
    private javax.swing.JComboBox<String> cb_TallaRopa;
    private javax.swing.JCheckBox checkBoxTerminos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTitulo2;
    private javax.swing.JLabel lb_Deportes;
    private javax.swing.JLabel lb_Pagina;
    private javax.swing.JLabel lb_TallaPie;
    private javax.swing.JLabel lb_TallaRopa;
    // End of variables declaration//GEN-END:variables
}
