/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Decathlon.gui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Datos1 extends javax.swing.JDialog {
    private PantallaPrincipal pantallaPrincipal;
    
    private String nombre;
    private String apellidos;
    private String genero;
    private int edad;
    private String dni;
    private String correo;

    /**
     * Creates new form Datos1
     */
    public Datos1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;
        initComponents();
    }
    
    private boolean validarDatos(){
        if(!(this.nombre.isEmpty() || this.apellidos.isEmpty() || this.dni.isEmpty() || this.correo.isEmpty())){
            if(validarEdad()){
                if(validarDNI()){
                    if(validarCorreo()){
                        return true;
                    }
                }
            }
        } else{
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacíos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    
    private boolean validarEdad(){
        try {
            this.edad = Integer.valueOf(tf_Edad.getText());
            return true;
        } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La edad debe ser un número entero", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    private boolean validarDNI(){
        Pattern patron = Pattern.compile("[0-9]{7,8}[A-Z a-z]");
        Matcher mat = patron.matcher(this.dni);
        if(mat.matches()){
            return true;
        } else{
            JOptionPane.showMessageDialog(this, "El formato de DNI no es correcto", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    
    private boolean validarCorreo(){
        String regx = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regx);
        //Iterate emails array list  
        Matcher mather = pattern.matcher(this.correo);
 
        if (mather.find() == true) { 
            return true;        
        } else {
            JOptionPane.showMessageDialog(this, "El correo no es válido", "ERROR", JOptionPane.ERROR_MESSAGE);            
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        lb_Nombre = new javax.swing.JLabel();
        lb_Apellido = new javax.swing.JLabel();
        tf_Apellidos = new javax.swing.JTextField();
        lb_Edad = new javax.swing.JLabel();
        tf_Edad = new javax.swing.JTextField();
        lb_Genero = new javax.swing.JLabel();
        lb_Dni = new javax.swing.JLabel();
        tf_Dni = new javax.swing.JTextField();
        lb_Correo = new javax.swing.JLabel();
        tf_Correo = new javax.swing.JTextField();
        cb_Genero = new javax.swing.JComboBox<>();
        bt_Cancelar = new javax.swing.JButton();
        bt_Siguiente1 = new javax.swing.JButton();
        lb_Pagina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo1.setBackground(new java.awt.Color(51, 102, 255));
        lbTitulo1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo1.setText("DATOS PERSONALES");
        lbTitulo1.setOpaque(true);

        tf_Nombre.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreActionPerformed(evt);
            }
        });

        lb_Nombre.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Nombre.setText("Nombre:");

        lb_Apellido.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Apellido.setText("Apellidos:");

        tf_Apellidos.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lb_Edad.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Edad.setText("Edad:");

        tf_Edad.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lb_Genero.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Genero.setText("Género:");

        lb_Dni.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Dni.setText("DNI:");

        tf_Dni.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lb_Correo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Correo.setText("Correo:");

        tf_Correo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        cb_Genero.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cb_Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Otro" }));

        bt_Cancelar.setBackground(new java.awt.Color(255, 153, 153));
        bt_Cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bt_Cancelar.setText("Cancelar");
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        bt_Siguiente1.setBackground(new java.awt.Color(204, 255, 204));
        bt_Siguiente1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bt_Siguiente1.setText("Siguiente");
        bt_Siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Siguiente1ActionPerformed(evt);
            }
        });

        lb_Pagina.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lb_Pagina.setText("Página 1/2");
        lb_Pagina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lb_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                        .addComponent(tf_Apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                        .addComponent(tf_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                        .addComponent(cb_Genero, 0, 359, Short.MAX_VALUE)
                                        .addComponent(tf_Dni)
                                        .addComponent(tf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)
                                    .addComponent(bt_Siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lb_Pagina))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_Apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_Genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_Siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_Pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_CancelarActionPerformed

    private void bt_Siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Siguiente1ActionPerformed
        
        this.nombre = tf_Nombre.getText();
        this.apellidos = tf_Apellidos.getText();
        this.genero = cb_Genero.getSelectedItem().toString();
        this.dni = tf_Dni.getText();
        this.correo = tf_Correo.getText();
        if(validarDatos()){
            try {
                if(this.edad > 0){
                    Datos2 datos2 = new Datos2(this,true);
                    datos2.setVisible(true);
                } else{
                    JOptionPane.showMessageDialog(this, "La edad debe ser un número mayor a 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bt_Siguiente1ActionPerformed

    

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public int getEdad() {
        return edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_Siguiente1;
    private javax.swing.JComboBox<String> cb_Genero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lb_Apellido;
    private javax.swing.JLabel lb_Correo;
    private javax.swing.JLabel lb_Dni;
    private javax.swing.JLabel lb_Edad;
    private javax.swing.JLabel lb_Genero;
    private javax.swing.JLabel lb_Nombre;
    private javax.swing.JLabel lb_Pagina;
    private javax.swing.JTextField tf_Apellidos;
    private javax.swing.JTextField tf_Correo;
    private javax.swing.JTextField tf_Dni;
    private javax.swing.JTextField tf_Edad;
    private javax.swing.JTextField tf_Nombre;
    // End of variables declaration//GEN-END:variables
}
